---

- name: Get workspaceone packages
  ansible.builtin.get_url:
    url: "https://packages.vmware.com/wsone/workspaceone-intelligent-hub-amd64-22.06.0.7.deb"
    dest: '/tmp/workspaceone.deb'

- name: Install package
  ansible.builtin.apt:
    deb: '/tmp/workspaceone.deb'
  become: true
  